name: Add PR Template Comment
on:
  issues:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Extract form data
        id: form
        run: |
          # Extract the issue body
          echo "Raw issue body:"
          echo "${{ github.event.issue.body }}"

          # Parse the inputs from the form
          NAME=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Name\n).*' || echo "[Your submission name]")
          DESCRIPTION=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Description\n).*' || echo "[Your description]")
          LINK=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Link\n).*' || echo "[Your link]")
          LAYER=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Layer\n).*' || echo "[Selected layer]")
          COMPONENTS=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Components\n).*' || echo "[Component categories]")
          LICENSE=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### License\n).*' || echo "[Selected license type]")
          TYPE=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Type\n).*' || echo "[Selected type]")
          USAGE=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Usage\n).*' || echo "[Usage description]")

          # Output extracted values or defaults
          echo "::set-output name=name::$NAME"
          echo "::set-output name=description::$DESCRIPTION"
          echo "::set-output name=link::$LINK"
          echo "::set-output name=layer::$LAYER"
          echo "::set-output name=components::$COMPONENTS"
          echo "::set-output name=license::$LICENSE"
          echo "::set-output name=type::$TYPE"
          echo "::set-output name=usage::$USAGE"

      - name: Add Tech Stack PR Template Comment
        if: contains(github.event.issue.labels.*.name, 'tech-stack')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for submitting a new tech stack item! Here's a template for the PR that you or anyone else can submit to add this to `techStackData.ts`:

            ```typescript
            {
              Name: '${{ steps.form.outputs.name }}',
              Description: '${{ steps.form.outputs.description }}',
              Link: '${{ steps.form.outputs.link }}',
              Layer: '${{ steps.form.outputs.layer }}',
              Components: '${{ steps.form.outputs.components }}',
              License: '${{ steps.form.outputs.license }}',
            },
            ```

            To submit:
            1. Fork the repository
            2. Add your entry to the end of the array in `src/data/techStackData.ts`
            3. Create a pull request

            Make sure to:
            - Match the exact format of existing entries
            - Include a comment in your PR linking back to this issue

      - name: Add Model PR Template Comment
        if: contains(github.event.issue.labels.*.name, 'model')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for submitting a new model! Here's a template for the PR that you or anyone else can submit to add this to `modelsData.ts`:

            ```typescript
            {
              Name: '${{ steps.form.outputs.name }}',
              Description: '${{ steps.form.outputs.description }}',
              Link: '${{ steps.form.outputs.link }}',
              Type: '${{ steps.form.outputs.type }}',
              Usage: '${{ steps.form.outputs.usage }}',
              License: '${{ steps.form.outputs.license }}',
            },
            ```

            To submit:
            1. Fork the repository
            2. Add your entry to the end of the array in `src/data/modelsData.ts`
            3. Create a pull request

            Make sure to:
            - Match the exact format of existing entries
            - Include a comment in your PR linking back to this issue
