name: Add PR Template Comment
on:
  issues:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Tech Stack PR Template Comment
        if: contains(github.event.issue.labels.*.name, 'tech-stack')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for submitting a new tech stack item! Here's a template for the PR that you or anyone else can submit to add this to `techStackData.ts`:

            ```typescript
            {
              Name: '[Your submission name]',
              Description: '[Your description]',
              Link: '[Your link]',
              Layer: '[Selected layer]',
              Components: '[Component categories]',
              License: '[Selected license]',
            },
            ```

            To submit:
            1. Fork the repository
            2. Add your entry to the end of the array in `src/data/techStackData.ts`
            3. Create a pull request

            Make sure to:
            - Match the exact format of existing entries
            - Include a comment in your PR linking back to this issue

      - name: Add Model PR Template Comment
        if: contains(github.event.issue.labels.*.name, 'model')
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for submitting a new model! Here's a template for the PR that you or anyone else can submit to add this to `modelsData.ts`:

            ```typescript
            {
              Name: '[Your submission name]',
              Description: '[Your description]',
              Link: '[Your link]',
              Type: '[Selected type]',
              Usage: '[Usage description]',
              License: '[Selected license]',
            },
            ```

            To submit:
            1. Fork the repository
            2. Add your entry to the end of the array in `src/data/modelsData.ts`
            3. Create a pull request

            Make sure to:
            - Match the exact format of existing entries
            - Include a comment in your PR linking back to this issue
